FROM ubuntu

RUN apt-get update && apt-get upgrade

RUN apt-get install -y software-properties-common

RUN add-apt-repository universe

RUN apt-get update && apt-get upgrade

WORKDIR /app

RUN apt-get install -y g++

RUN apt-get update && apt-get install -y neofetch

RUN apt-get install -y git

RUN apt-get install -y python3

RUN apt-get install -y vim

RUN apt-get install -y nano

COPY . .

RUN g++ -o nyan main.cpp

RUN chmod +x ./nyan



